name: hyp3-autorift-isce3
channels:
#  - hyp3
  - conda-forge
  - nodefaults
dependencies:
  - boto3
  - botocore
  - python>=3.9
  - pip
  # For packaging, and testing
  - build
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - pillow
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - responses
  - setuptools>=61
  - setuptools_scm>=6.2
  # For running
  - gdal>=3
  - h5netcdf
  - hyp3lib>=3,<4
  - isce3>=0.13
  - autorift=1.5.0
  - opencv
  - boto3
  - matplotlib-base
  - netCDF4
  - numpy>=1.20,<2.0
  - pyproj
  - requests>=2.0
  - scipy
  - shapely>=2
  - xarray
  - packaging>=21.0
  - lxml>=4.8
  - tifffile>=2024.0.0
  - asf_search
  - dateparser!=1.1.0
  - dem_stitcher
  - burst2safe #get the develop version so it doesn't look for iw2
