name: hyp3-autorift
channels:
  - hyp3
  - conda-forge
  - nodefaults
dependencies:
  - boto3
  - botocore
  - python>=3.8
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - pillow
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - responses
  - setuptools
  - setuptools_scm
  - wheel
  # For running
  - gdal>=3
  - hyp3lib=1.7.0
  - isce2=2.6.2.dev1
  - autorift=1.5.0.dev1
  - opencv
  - boto3
  - matplotlib-base
  - netCDF4
  - numpy
  - requests
  - scipy
