name: hyp3-autorift
channels:
  - hyp3
  - conda-forge
  - nodefaults
dependencies:
  - boto3
  - botocore
  - python>=3.9,<3.10  # Top pin to fix ISCE2 incompatibility: https://github.com/isce-framework/isce2/issues/458
  - pip
  # For packaging, and testing
  - build
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - pillow
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - responses
  - setuptools>=61
  - setuptools_scm>=6.2
  # For running
  - gdal>=3
  - h5netcdf
  - hyp3lib>=3,<4
  - isce2=2.6.1.dev7
  - autorift=1.5.0
  - opencv
  - boto3
  - matplotlib-base
  - netCDF4
  - numpy<1.24 # https://github.com/isce-framework/isce2/pull/639
  - pyproj
  - requests
  - scipy
  - xarray
