name: hyp3-autorift
channels:
  - conda-forge
  - hyp3
  - nodefaults
dependencies:
  - boto3
  - botocore
  - python=3.8
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - pillow
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - responses
  - setuptools
  - setuptools_scm
  - wheel
  # For running
  - gdal>=3
  - hyp3lib=1.6.7
  - isce2=2.5.1.dev7
  - autorift=1.3.1
  - boto3
  - matplotlib-base
  - netCDF4
  - numpy
  - requests
  - scikit-image  # missing autoRIFT dep
  - scipy
