[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "hyp3_autorift"
requires-python = ">=3.8"
authors = [
    {name="ASF APD/Tools Team", email="uaf-asf-apd@alaska.edu"},
]
description = "A HyP3 plugin for feature tracking processing with AutoRIFT-ISCE"
readme = "README.md"
license = {text = "BSD-3-Clause"}
classifiers=[
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    'boto3',
    'botocore',
    'gdal',
    'h5netcdf',
    'hyp3lib==1.7.0',
    'matplotlib',
    'netCDF4',
    'numpy',
    'pyproj',
    'requests',
    'scipy',
    'xarray',
]
dynamic = ["version"]

[project.optional-dependencies]
develop = [
    'flake8',
    'flake8-import-order',
    'flake8-blind-except',
    'flake8-builtins',
    'pillow',
    'pytest',
    'pytest-cov',
    'pytest-console-scripts',
    'responses',
]

[project.scripts]
hyp3_autorift = "hyp3_autorift.process:main"
s1_correction = "hyp3_autorift.s1_correction:main"

[project.urls]
Homepage = "https://github.com/ASFHyP3/hyp3-autorift"
"Bug Tracker" = "https://github.com/ASFHyP3/hyp3-autorift/issues"
Documentation = "https://hyp3-docs.asf.alaska.edu"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools_scm]
