on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  call-release-checklist-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release-checklist-comment.yml@v0.20.0
    permissions:
      pull-requests: write
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
