name: Static analysis

on: push

jobs:
  call-secrets-analysis-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.22.0
    permissions:
      contents: read

  call-pixi-tasks-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-pixi-tasks.yml@v0.22.0
    with:
      tasks: >-
        ["mypy", "ruff check --output-format=github", "ruff format --diff"]
    permissions:
      contents: read
