name: Test and build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-pytest-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-pytest.yml@v0.4.0
    with:
      local_package_name: hyp3_autorift
      conda_env_name: hyp3-autorift

  call-version-info-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-version-info.yml@v0.4.0
    with:
      conda_env_name: hyp3-autorift

  call-docker-ghcr-workflow:
    needs: call-version-info-workflow
    uses: ASFHyP3/actions/.github/workflows/reusable-docker-ghcr.yml@v0.4.0
    with:
      version_tag: ${{ needs.call-version-info-workflow.outputs.version_tag }}
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
