name: Test and build

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-pytest-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-pytest.yml@v0.20.0
    permissions:
      contents: read
    with:
      local_package_name: hyp3_autorift
      python_versions: >-
        ["3.10", "3.11", "3.12"]

  call-version-info-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-version-info.yml@v0.20.0
    permissions:
      contents: read
    with:
      python_version: '3.10'

  call-docker-ghcr-workflow:
    needs: call-version-info-workflow
    uses: ASFHyP3/actions/.github/workflows/reusable-docker-ghcr.yml@v0.20.0
    permissions:
      contents: read
      packages: write
    with:
      version_tag: ${{ needs.call-version-info-workflow.outputs.version_tag }}
      user: ${{ github.actor }}
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
